language: java
sudo: false

matrix:
  include:
# 10
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL
# 8
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8
    - env: JDK='OpenJDK 8'
      jdk: openjdk8
# 7
    - env: JDK='OpenJDK 7'
      jdk: openjdk7

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
  - ./mvnw install -q -DskipTests=true

install: true

before_script:
  - export CARGO_MAVEN_PLUGIN_VERSION=`mvn -B help:evaluate -Dexpression=cargo-maven2-plugin.version | grep -v '^\['`
  - ./mvnw dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_MAVEN_PLUGIN_VERSION}:war -Dmdep.stripVersion=true
  - java -jar ./target/dependency/cargo-daemon-webapp.war &

script:
  - |
    if [ "${TRAVIS_JDK_VERSION}" != "openjdk7" ]; then
      ./mvnw -U clean verify cargo:daemon-start -P tomcat90
      ./mvnw -U test -P itest
    else
      ./mvnw -U clean verify
    fi

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
  - secure: OYpjRGu1vnh+yrWqdpaF1nWAzshvlFzh9frQGZv51PCrB+xnwY6SLiwtrlNZ9NKp60Buoxf3YySAml2xG86Y0gUCVjUsFlWg0mBFs1Hvnv6lxUVla6ZjiQ+C9wSavjky6jPbGrBjHd2uXvdUnElMzJc7j6Czm6BigmAaivPfwE0=
  - secure: n8R+jUI2M/SY3pfiVOP95jLbkMXSIrAVhJ6ttTyr9k9OpLdIiP0LJ/Ccv/lNawx0TBlbApcZsc+fh3YZC5QJOl4+2pT9yc7+nULv8LlWoDVjWy+31rD6UJsxgGvADks1gs8SYvW2oHP2vNd8GUpNG6W3hmBkQm80wi6ssAxysZM=
